### PR TITLE
enabling typescript typings support

### PR DESCRIPTION
**Pull request by mrapptambour**

### CODE REVIEW

**Comment by zacronos** [comment]
LGTM

**Comment by mrapptambour** [comment]
@zacronos I have a couple updates to expose some of the data types more direct...one sec.

**Comment by mrapptambour** [comment]
@zacronos what is `LGTM`, sorry to ask?

**Comment by zacronos** [comment]
Oops, sorry!  Make a new PR with the changes and I'll merge them too.  (LGTM: Looks Good To Me)

**Pull request merged**
