### PR TITLE
missed dts files add

### PR DESCRIPTION
**Pull request by mrapptambour**

### CODE REVIEW

**Comment by mrapptambour** [comment]
@zacronos here is the miss.

**Comment by mrapptambour** [comment]
Didn't see the files usage vs `.npmignore`

**Comment by mrapptambour** [comment]
@zacronos what is the publishing schedule you have to make it a 5.0.4 upgrade?

**Comment by zacronos** [comment]
hah, it's completely ad-hoc.  I'll make it 5.1.0 later today

**Comment by zacronos** [comment]
@mrapptambour v5.1.0 published

**Pull request merged**
